server {
    listen 80;
    root /var/www/html/PROJET/UTILISATEUR;
    index USR-index.php;

    location / {
        try_files $uri $uri/ /USR-index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index USR-index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}