server {
    listen 80;
    root /var/www/html;
    index PROJET/UTILISATEUR/USR-index.php;

    location / {
        try_files $uri $uri/ /PROJET/UTILISATEUR/USR-index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index PROJET/UTILISATEUR/USR-index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}