server {
    listen 80;
    root /var/www/html/PROJET;
    index UTILISATEUR/USR-index.php;

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /UTILISATEUR/USR-index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index UTILISATEUR/USR-index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}